// Nav hamburger
const hamburger = document.getElementById('hamburger');
const mobileMenu = document.getElementById('mobileMenu');
if (hamburger) {
  hamburger.addEventListener('click', () => {
    hamburger.classList.toggle('active');
    mobileMenu.classList.toggle('show');
  });
}

// Fade-in scroll
const faders = document.querySelectorAll('.fade-in');
const appearOnScroll = new IntersectionObserver(
  entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) entry.target.classList.add('visible');
    });
  },
  { threshold: 0.2 }
);
faders.forEach(f => appearOnScroll.observe(f));

// Get Started scroll
const getBtn = document.getElementById('getStartedBtn');
if (getBtn) {
  getBtn.addEventListener('click', () => document.querySelector('#try-it').scrollIntoView({ behavior: 'smooth' }));
}

// Code Generator simulation
const generateBtn = document.getElementById('generateBtn');
const aiThinking = document.getElementById('aiThinking');
const codeTerminal = document.getElementById('codeTerminal');
const copyBtn = document.getElementById('copyBtn');

if (generateBtn) {
  generateBtn.addEventListener('click', () => {
    const prompt = document.getElementById('promptInput').value.trim();
    if (!prompt) return alert("Enter a prompt first!");
    aiThinking.style.display = "block";
    codeTerminal.textContent = "";
    setTimeout(() => {
      aiThinking.style.display = "none";
      const code = `import pytest\n\ndef test_${prompt.replace(/\s+/g, "_")}():\n    assert True  # Auto-generated by QA INTELLIGENCE`;
      codeTerminal.textContent = code;
      hljs.highlightElement(codeTerminal);
    }, 1200);
  });
}

if (copyBtn) {
  copyBtn.addEventListener('click', () => {
    navigator.clipboard.writeText(codeTerminal.textContent);
    copyBtn.textContent = "Copied!";
    setTimeout(() => (copyBtn.textContent = "Copy"), 1500);
  });
}

// Pricing selection
document.querySelectorAll('.pricing-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.pricing-card').forEach(c => c.classList.remove('popular'));
    btn.closest('.pricing-card').classList.add('popular');
  });
});

// FAQ toggle
document.querySelectorAll('.faq-card').forEach(card => {
  const header = card.querySelector('.faq-header');
  header.addEventListener('click', () => {
    card.classList.toggle('open');
    const icon = card.querySelector('.faq-icon');
    icon.textContent = card.classList.contains('open') ? "-" : "+";
  });
});

// Contact validation
const sendBtn = document.getElementById('sendBtn');
const statusMsg = document.getElementById('statusMsg');
if (sendBtn) {
  sendBtn.addEventListener('click', () => {
    const n = document.getElementById('name').value.trim();
    const e = document.getElementById('email').value.trim();
    const m = document.getElementById('message').value.trim();
    if (!n || !e || !m) {
      statusMsg.textContent = "Please fill all fields.";
      statusMsg.style.color = "red";
      return;
    }
    statusMsg.textContent = "Sending...";
    statusMsg.style.color = "var(--brand-color)";
    setTimeout(() => {
      statusMsg.textContent = "✅ Message sent!";
      statusMsg.style.color = "lime";
    }, 1500);
  });
}
